"""Public package interface for the Myli agent harness."""

from ._models import LiteLLMMainModel, LiteLLMVisionModel, OutputMode
from .adapters import FunctionAssetSearch, FunctionRenderer
from .contracts import (
    EVENT_KINDS,
    AgentTool,
    Allow,
    Asset,
    AssetSearchProvider,
    CandidateContext,
    CandidatePolicy,
    CandidateValidator,
    DefaultModelContextPolicy,
    Defer,
    DesignRenderer,
    DesignSpec,
    EventHandler,
    FailureMode,
    InputArtifact,
    InputArtifactLoader,
    InputMigrator,
    MainModel,
    Message,
    ModelCallPurpose,
    ModelCallTrace,
    ModelContext,
    ModelContextPolicy,
    ModelRequest,
    ModelResponse,
    PreviewLoader,
    Reject,
    RenderedArtifact,
    RunEvent,
    RunResult,
    RunUsage,
    StepHandler,
    StepTrace,
    ToolCall,
    ToolContext,
    ToolDecision,
    ToolDefinition,
    ToolMiddleware,
    ToolOutcome,
    TraceRedactor,
    VisionModel,
    VisualReviewImage,
    VisualReviewRequest,
)
from .errors import (
    ConfigurationError,
    DesignValidationError,
    JsonPatchError,
    ModelProtocolError,
    MyliError,
    ProviderConnectionError,
    ProviderError,
    ProviderRateLimitError,
    ProviderTimeoutError,
    RunLimitExceeded,
    RunTimeoutError,
    ToolExecutionError,
)
from .harness import HarnessLimits, Myli
from .json_patch import JsonPatchLimits, apply_json_patch


__version__ = "0.3.0"

__all__ = [
    "EVENT_KINDS",
    "AgentTool",
    "Allow",
    "Asset",
    "AssetSearchProvider",
    "CandidateContext",
    "CandidatePolicy",
    "CandidateValidator",
    "ConfigurationError",
    "Defer",
    "DefaultModelContextPolicy",
    "DesignRenderer",
    "DesignSpec",
    "DesignValidationError",
    "EventHandler",
    "FailureMode",
    "FunctionAssetSearch",
    "FunctionRenderer",
    "HarnessLimits",
    "InputArtifact",
    "InputArtifactLoader",
    "InputMigrator",
    "JsonPatchError",
    "JsonPatchLimits",
    "LiteLLMMainModel",
    "LiteLLMVisionModel",
    "MainModel",
    "Message",
    "ModelCallPurpose",
    "ModelCallTrace",
    "ModelContext",
    "ModelContextPolicy",
    "ModelProtocolError",
    "ModelRequest",
    "ModelResponse",
    "Myli",
    "MyliError",
    "OutputMode",
    "PreviewLoader",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderTimeoutError",
    "Reject",
    "RenderedArtifact",
    "RunEvent",
    "RunLimitExceeded",
    "RunResult",
    "RunUsage",
    "RunTimeoutError",
    "StepHandler",
    "StepTrace",
    "ToolCall",
    "ToolContext",
    "ToolDecision",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolMiddleware",
    "ToolOutcome",
    "TraceRedactor",
    "VisualReviewImage",
    "VisualReviewRequest",
    "VisionModel",
    "apply_json_patch",
    "__version__",
]
